[workspace]
members = ["src/ethereum-canister", "src/contracts-abi", "src/interface"]
resolver = "2"

[workspace.dependencies]
contracts-abi = { path = "src/contracts-abi" }
ethers-contract = { version = "2.0.8", default-features = false, features = [
  "abigen",
] }
ethers-core = "2.0.8"
eyre = "0.6.8"
helios_client = { package = "client", git = "https://github.com/eigerco/helios", rev = "a7173b2" }
helios_common = { package = "common", git = "https://github.com/eigerco/helios", rev = "a7173b2" }
helios_config = { package = "config", git = "https://github.com/eigerco/helios", rev = "a7173b2" }
helios_execution = { package = "execution", git = "https://github.com/eigerco/helios", rev = "a7173b2" }
interface = { path = "src/interface" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[patch.crates-io]
ethers-contract = { git = "https://github.com/oblique/ethers-rs", rev = "3740d34" }
ethers-contract-abigen = { git = "https://github.com/oblique/ethers-rs", rev = "3740d34" }
ethers-contract-derive = { git = "https://github.com/oblique/ethers-rs", rev = "3740d34" }
ethers-core = { git = "https://github.com/oblique/ethers-rs", rev = "3740d34" }
