[workspace]
members = ["src/ethereum_canister_backend"]
resolver = "2"

[workspace.dependencies]
helios_client = { package = "client", path = "../helios/client" }
helios_common = { package = "common", path = "../helios/common" }
helios_config = { package = "config", path = "../helios/config" }
